#cloud-config

ssh_deletekeys: true
ssh_genkeytypes:
  - ed25519
  - ecdsa
  - rsa

package_update: true
packages:
  - git
  - openssh-server
  - openssh-client
  - python3
  - python3-venv
  - python3-pip
  - openmpi-bin
  - libopenmpi-dev

runcmd:
  - |
    set -eux
    systemctl restart ssh || systemctl restart sshd
    cd /opt/pw-lxd
    git pull && git checkout main
    .venv/bin/pip install --upgrade pip
    .venv/bin/pip install -e .
